#!/usr/bin/python2
# -*- coding: utf-8 -*-

#imports
import sys
import re
import datetime
import time
import random
import os.path
from os.path import expanduser

#set deafult folder
home = expanduser("~")

if os.path.exists(home+"/journal/entries.txt")==False:
    print "\nCreating file at ~/journal/entries.txt to store entries..."
    #create a folder
    try:
        if not os.path.exists(home+"/journal/"):
            os.makedirs(home+"/journal/")
            print("Directory created.")
    except OSError:
        print ("Error creating directory")

if len(sys.argv) > 2:
    print "too  many arguments"
elif len(sys.argv) < 2:
    print "no arguments given"
else:
    if sys.argv[1]=="help":
        print("* `journal new` to enter new journal entry.\n* `journal show` to see all entries")
    elif sys.argv[1]=="new":
      f = open(home+"/journal/entries.txt", "a+")
      userstrin=str(raw_input("Enter entry: "))
      now = datetime.datetime.now()
      date=now.strftime("%Y-%m-%d %H:%M")
      f.write("\n-------------------------\n"+date+"\n-------------------------\n"+userstrin+"\n")
      f.close()

    elif sys.argv[1]=="show":
      try:
        r = open(home+"/journal/entries.txt")
        line = r.readline()
        while line:
            print line
            line = r.readline()
        r.close()
      except IOError:
        print "Nothing is logged yet."

    else:
        print "I don't know that command."
